### ISSUE TITLE
Wrong dependency for Microsoft.DotNet.ProjectModel (>= 1.0.0-rc4-003206)

### ISSUE THREAD

**Issue by jurby** [BalassaMarton/dotnet-bump#1]
Hi, your NuGet package has dependency for Microsoft.DotNet.ProjectModel (>= 1.0.0-rc4-003206). But the version 1.0.0-rc4-003206  is not available in NuGet.org? Can you give me a direct or help, please? Thank you.

**Comment by BalassaMarton** [comment]
@jurby Thanks for pointing that out. I will try to change this dependency to the rc3 version that is available on NuGet.org. Until then, you can fetch the rc4 version from the ASP.NET vNext feed:
https://www.myget.org/F/aspnetvnext/api/v2

**Comment by BalassaMarton** [comment]
OK, the rc3 version works fine, I've updated `project.json`, and published the updated package.

**Comment by jurby** [comment]
Thank you very much for your advice and help. Take for very rapid change package.
