### ISSUE TITLE
 Is there any support for csproj?

### ISSUE THREAD

**Issue by neyromant** [BalassaMarton/dotnet-bump#2]

**Comment by BalassaMarton** [comment]
Not yet, but I need it too, and will implement it as soon as I have the time

**Comment by BalassaMarton** [comment]
Unfortunately, I can't write the `.csproj` file from the dotnet cli program. I managed to make it work with a custom MSBuild task, I will post it tomorrow.

**Comment by BalassaMarton** [comment]
I've created another tool, this time a MSBuild task that can bump the version in a `.csproj file`.
https://github.com/BalassaMarton/MSBump

**Comment by neyromant** [comment]
Thank you!
